#DOCKER COMPOSE FILE
version: '3'

services:
  atm:
   build: ./atm
   ports:
     - "8080:8080"
   #depends_on:
   #  - db
  admdashboard:
   build: ./admdashboard
   ports:
     - "3000:3000"
   depends_on:
     - atm
